/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as PairRouteImport } from './routes/pair'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as SettingsAgentsRouteImport } from './routes/settings.agents'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsKeybindingsRouteImport } from './routes/settings.keybindings'
import { Route as SettingsLocalEnvironmentRouteImport } from './routes/settings.local-environment'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsRemoteServersRouteImport } from './routes/settings.remote-servers'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as SettingsStatusBarRouteImport } from './routes/settings.status-bar'
import { Route as SettingsTerminalRouteImport } from './routes/settings.terminal'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatProjectEnvironmentIdProjectIdGitRouteImport } from './routes/_chat.project.$environmentId.$projectId.git'

const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAgentsRoute = SettingsAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({
  id: '/keybindings',
  path: '/keybindings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLocalEnvironmentRoute =
  SettingsLocalEnvironmentRouteImport.update({
    id: '/local-environment',
    path: '/local-environment',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsRemoteServersRoute = SettingsRemoteServersRouteImport.update({
  id: '/remote-servers',
  path: '/remote-servers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsStatusBarRoute = SettingsStatusBarRouteImport.update({
  id: '/status-bar',
  path: '/status-bar',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsTerminalRoute = SettingsTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => SettingsRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatProjectEnvironmentIdProjectIdGitRoute =
  ChatProjectEnvironmentIdProjectIdGitRouteImport.update({
    id: '/project/$environmentId/$projectId/git',
    path: '/project/$environmentId/$projectId/git',
    getParentRoute: () => ChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/local-environment': typeof SettingsLocalEnvironmentRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/remote-servers': typeof SettingsRemoteServersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/status-bar': typeof SettingsStatusBarRoute
  '/settings/terminal': typeof SettingsTerminalRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/project/$environmentId/$projectId/git': typeof ChatProjectEnvironmentIdProjectIdGitRoute
}
export interface FileRoutesByTo {
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/local-environment': typeof SettingsLocalEnvironmentRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/remote-servers': typeof SettingsRemoteServersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/status-bar': typeof SettingsStatusBarRoute
  '/settings/terminal': typeof SettingsTerminalRoute
  '/': typeof ChatIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/project/$environmentId/$projectId/git': typeof ChatProjectEnvironmentIdProjectIdGitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/settings/about': typeof SettingsAboutRoute
  '/settings/agents': typeof SettingsAgentsRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/local-environment': typeof SettingsLocalEnvironmentRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/remote-servers': typeof SettingsRemoteServersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/status-bar': typeof SettingsStatusBarRoute
  '/settings/terminal': typeof SettingsTerminalRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/_chat/project/$environmentId/$projectId/git': typeof ChatProjectEnvironmentIdProjectIdGitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pair'
    | '/settings'
    | '/settings/about'
    | '/settings/agents'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/local-environment'
    | '/settings/providers'
    | '/settings/remote-servers'
    | '/settings/source-control'
    | '/settings/status-bar'
    | '/settings/terminal'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/project/$environmentId/$projectId/git'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/pair'
    | '/settings'
    | '/settings/about'
    | '/settings/agents'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/local-environment'
    | '/settings/providers'
    | '/settings/remote-servers'
    | '/settings/source-control'
    | '/settings/status-bar'
    | '/settings/terminal'
    | '/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/project/$environmentId/$projectId/git'
  id:
    | '__root__'
    | '/_chat'
    | '/pair'
    | '/settings'
    | '/settings/about'
    | '/settings/agents'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/general'
    | '/settings/keybindings'
    | '/settings/local-environment'
    | '/settings/providers'
    | '/settings/remote-servers'
    | '/settings/source-control'
    | '/settings/status-bar'
    | '/settings/terminal'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
    | '/_chat/project/$environmentId/$projectId/git'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/agents': {
      id: '/settings/agents'
      path: '/agents'
      fullPath: '/settings/agents'
      preLoaderRoute: typeof SettingsAgentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keybindings': {
      id: '/settings/keybindings'
      path: '/keybindings'
      fullPath: '/settings/keybindings'
      preLoaderRoute: typeof SettingsKeybindingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/local-environment': {
      id: '/settings/local-environment'
      path: '/local-environment'
      fullPath: '/settings/local-environment'
      preLoaderRoute: typeof SettingsLocalEnvironmentRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/remote-servers': {
      id: '/settings/remote-servers'
      path: '/remote-servers'
      fullPath: '/settings/remote-servers'
      preLoaderRoute: typeof SettingsRemoteServersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/status-bar': {
      id: '/settings/status-bar'
      path: '/status-bar'
      fullPath: '/settings/status-bar'
      preLoaderRoute: typeof SettingsStatusBarRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/terminal': {
      id: '/settings/terminal'
      path: '/terminal'
      fullPath: '/settings/terminal'
      preLoaderRoute: typeof SettingsTerminalRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/project/$environmentId/$projectId/git': {
      id: '/_chat/project/$environmentId/$projectId/git'
      path: '/project/$environmentId/$projectId/git'
      fullPath: '/project/$environmentId/$projectId/git'
      preLoaderRoute: typeof ChatProjectEnvironmentIdProjectIdGitRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
  ChatProjectEnvironmentIdProjectIdGitRoute: typeof ChatProjectEnvironmentIdProjectIdGitRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
  ChatProjectEnvironmentIdProjectIdGitRoute:
    ChatProjectEnvironmentIdProjectIdGitRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAgentsRoute: typeof SettingsAgentsRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute
  SettingsLocalEnvironmentRoute: typeof SettingsLocalEnvironmentRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsRemoteServersRoute: typeof SettingsRemoteServersRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
  SettingsStatusBarRoute: typeof SettingsStatusBarRoute
  SettingsTerminalRoute: typeof SettingsTerminalRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAgentsRoute: SettingsAgentsRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsKeybindingsRoute: SettingsKeybindingsRoute,
  SettingsLocalEnvironmentRoute: SettingsLocalEnvironmentRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsRemoteServersRoute: SettingsRemoteServersRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
  SettingsStatusBarRoute: SettingsStatusBarRoute,
  SettingsTerminalRoute: SettingsTerminalRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
