import type { PullRequestsContext, PullRequestsListRow } from "@bibcode/contracts";
export const context: Extract<PullRequestsContext, { status: "available" }> = {
  status: "available",
  provider: "github",
  host: "github.com",
  hostVersion: null,
  repository: "owner/repo",
  defaultBranch: "main",
  account: { login: "alice", name: "Alice", isBot: false },
  repositoryPermission: "write",
  webUrl: "https://github.com/owner/repo",
  mergePolicy: {
    methods: ["merge"],
    defaultMethod: "merge",
    deleteBranchDefault: false,
    autoMergeAllowed: false,
    requiresPipelineSuccess: false,
    requiresResolvedDiscussions: false,
  },
  capabilities: {
    vocabulary: {
      pullRequest: "pull request",
      pullRequests: "pull requests",
      checks: "Checks",
      filesChanged: "Files changed",
      reviewer: "Reviewers",
      approve: "Approve",
      requestChanges: "Request changes",
    },
    requestChanges: true,
    revokeApproval: false,
    removeOwnChangeRequest: false,
    dismissReview: true,
    applySuggestion: true,
    minimizeComment: true,
    deletePullRequest: false,
    lockReasons: [],
    updateBranchMethods: ["merge"],
    mergeMethodsSource: "per_pull_request",
    autoMergeLabel: "Auto-merge",
    reviewerStates: true,
    closedTabIncludesMerged: true,
  },
};
export const row: PullRequestsListRow = {
  number: 14,
  title: "Fix connection recovery",
  state: "open",
  isDraft: false,
  author: { login: "alice", name: "Alice Example", isBot: false },
  createdAt: "2026-09-19T12:00:00Z",
  updatedAt: "2026-09-20T12:00:00Z",
  mergedAt: null,
  closedAt: null,
  headBranch: "fix",
  baseBranch: "main",
  labels: [{ name: "bug", color: "d73a4a", description: "Fix a bug" }],
  reviewDecision: "approved",
  checksSummary: "success",
  commentCount: 3,
  approvals: null,
  unresolvedThreads: null,
  url: "https://github.com/owner/repo/pull/14",
};
