// @effect-diagnostics nodeBuiltinImport:off - Actual installer source with inert filesystem/Git ports; no process execution.
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";
import * as NodeModule from "node:module";
import * as NodeVM from "node:vm";
import { expect, it } from "vite-plus/test";
import {
  extendOwnedClaudeVisualFixture,
  extendOwnedCodexVisualFixture,
} from "./release-visual-provider-chat-fixture.ts";
import {
  extendOwnedCursorQuestionFixture,
  cursorQuestionFixtureSelection,
} from "./release-visual-cursor-question-fixture.ts";
import { desktopActivityFixture, desktopActivityMarkerFileName } from "./activity-events.ts";
import { desktopUiFixture } from "./test-project.ts";

const source = NodeFS.readFileSync(new URL("./test-project.ts", import.meta.url), "utf8");
function original(name: string, next: string) {
  const start = source.indexOf("const " + name + " = String.raw`");
  const end = source.indexOf(next, start);
  expect(start).toBeGreaterThan(0);
  expect(end).toBeGreaterThan(start);
  return NodeVM.runInNewContext(source.slice(start, end) + "\n" + name, {
    STREAMED_RESPONSE: desktopUiFixture.streamedResponse,
    desktopActivityFixture,
    desktopActivityMarkerFileName,
    SLOW_TURN_RELEASE_FILE_NAME: ".bibcode-e2e-slow-turn-release",
  }) as string;
}
const fixtureSources = {
  codexFixtureSource: original("codexFixtureSource", "const providerInputLogFixtureSource"),
  claudeFixtureSource: original("claudeFixtureSource", "const cursorFixtureSource"),
  cursorFixtureSource: original("cursorFixtureSource", "const grokFixtureSource"),
  grokFixtureSource: original("grokFixtureSource", "const opencodeFixtureSource"),
  opencodeFixtureSource: original("opencodeFixtureSource", "function writeExecutable"),
};

it("installs only the fixed provider sources and preserves all default generated bytes", () => {
  const files = new Map<string, string>();
  const start = source.indexOf("function createProviderShims("),
    end = source.indexOf("function writeProviderSettings(", start);
  const install = NodeVM.runInNewContext(
    NodeModule.stripTypeScriptTypes(source.slice(start, end)) + "\ncreateProviderShims",
    {
      ...fixtureSources,
      extendOwnedClaudeVisualFixture,
      extendOwnedCodexVisualFixture,
      extendOwnedCursorQuestionFixture,
      NodePath,
      NodeFS: {
        writeFileSync: (path: string, bytes: string) => files.set(NodePath.basename(path), bytes),
      },
      providerInputLogFixtureSource: "inert-log",
      nativeActionLogFixtureSource: "inert-actions",
      writeExecutable: (path: string, bytes: string) => files.set(NodePath.basename(path), bytes),
      process: { execPath: "/owned/node" },
    },
  ) as (...args: unknown[]) => void;
  install("/owned/shims", false);
  expect(files.get("codex-fixture.mjs")).toBe(fixtureSources.codexFixtureSource);
  expect(files.get("claude-fixture.mjs")).toBe(fixtureSources.claudeFixtureSource);
  const defaults = new Map(files);
  files.clear();
  install("/owned/shims", false, undefined, "provider-chat-v1");
  expect(files.get("codex-fixture.mjs")).toContain("ownedVisualCodexReasoning");
  expect(files.get("claude-fixture.mjs")).toContain("ownedVisualClaudeHandler");
  for (const [name, value] of defaults)
    if (!name.startsWith("codex-fixture") && !name.startsWith("claude-fixture"))
      expect(files.get(name)).toBe(value);
});

it.each([
  { CI: undefined, provider: "provider-chat-v1", cursor: undefined },
  { CI: "false", provider: "provider-chat-v1", cursor: undefined },
  { CI: "true", provider: "unknown", cursor: undefined },
  { CI: "true", provider: null, cursor: undefined },
  { CI: "true", provider: "provider-chat-v1", cursor: cursorQuestionFixtureSelection },
])("refuses unknown/non-CI/mixed provider admission before any filesystem port %#", (row) => {
  let touched = 0;
  const start = source.indexOf("export function prepareDesktopUiTestContext("),
    end = source.indexOf("export function archiveAndCleanupDesktopUiTestContext(", start);
  const prepare = NodeVM.runInNewContext(
    NodeModule.stripTypeScriptTypes(source.slice(start, end)).replace(/^export /gm, "") +
      "\nprepareDesktopUiTestContext",
    {
      cursorQuestionFixtureSelection,
      FIXTURE_PROJECT_NAME: desktopUiFixture.projectName,
      process: { platform: "linux" },
      desktopUiHostTemporaryDirectory: () => "/owned/tmp",
      NodePath,
      NodeOS: { tmpdir: () => "/owned/tmp" },
      NodeFS: {
        mkdirSync: () => {
          touched++;
          throw new Error("Inert filesystem touched");
        },
      },
    },
  ) as (...args: unknown[]) => unknown;
  expect(() =>
    prepare(
      {
        CI: row.CI,
        BIBCODE_E2E_RUN_ROOT: "/owned/run",
        BIBCODE_E2E_ARTIFACT_DIR: "/owned/artifacts",
      },
      "/owned/tmp",
      row.cursor,
      row.provider,
    ),
  ).toThrow("Owned provider chat fixture refused.");
  expect(touched).toBe(0);
});
